In [9]:
import pandas as pd

m = pd.read_hdf("../data/measured/imaging/round_1.h5")

needle = "MIC1227_CP_Batch1_Plate1B_1_MMStack_A2-Site_10"  # 파일명 일부만
hit = m[m["path-DNA"].astype(str).str.contains(needle, na=False)]

print("matches:", len(hit))
display(hit.head())

# 치료 정보로 보이는 컬럼들만 추려서 보기
cand_cols = [c for c in m.columns if any(k in c.lower() for k in
            ["pert", "treat", "compound", "drug", "moa", "dose", "time", "control"])]
display(hit[cand_cols].head())

matches: 431

,filename,source,batch,plate,well,site,path-DNA,path-RNA,path-AGP,path-Mito,...,sample registry,original_treatment,Dosage,Replicate,Group,Seen,ALIAS,Sample used for,Image file,Sample registry
4440,MIC1227_CP_Batch1_Plate1B_1_MMStack_A2-Site_10...,bai,APPrna_batch_1,1B,A2,102,measured/imaging/uint8/round_1/batch1/MIC1227_...,measured/imaging/uint8/round_1/batch1/MIC1227_...,measured/imaging/uint8/round_1/batch1/MIC1227_...,measured/imaging/uint8/round_1/batch1/MIC1227_...,...,CLL_BTCH_11971,Simvastatin::10uM::P046,10uM,3,treatment,False,NaN,NaN,NaN,NaN
4441,MIC1227_CP_Batch1_Plate1B_1_MMStack_A2-Site_10...,bai,APPrna_batch_1,1B,A2,102,measured/imaging/uint8/round_1/batch1/MIC1227_...,measured/imaging/uint8/round_1/batch1/MIC1227_...,measured/imaging/uint8/round_1/batch1/MIC1227_...,measured/imaging/uint8/round_1/batch1/MIC1227_...,...,CLL_BTCH_11971,Simvastatin::10uM::P046,10uM,3,treatment,False,NaN,NaN,NaN,NaN
4442,MIC1227_CP_Batch1_Plate1B_1_MMStack_A2-Site_10...,bai,APPrna_batch_1,1B,A2,102,measured/imaging/uint8/round_1/batch1/MIC1227_...,measured/imaging/uint8/round_1/batch1/MIC1227_...,measured/imaging/uint8/round_1/batch1/MIC1227_...,measured/imaging/uint8/round_1/batch1/MIC1227_...,...,CLL_BTCH_11971,Simvastatin::10uM::P046,10uM,3,treatment,False,NaN,NaN,NaN,NaN
4443,MIC1227_CP_Batch1_Plate1B_1_MMStack_A2-Site_10...,bai,APPrna_batch_1,1B,A2,102,measured/imaging/uint8/round_1/batch1/MIC1227_...,measured/imaging/uint8/round_1/batch1/MIC1227_...,measured/imaging/uint8/round_1/batch1/MIC1227_...,measured/imaging/uint8/round_1/batch1/MIC1227_...,...,CLL_BTCH_11971,Simvastatin::10uM::P046,10uM,3,treatment,False,NaN,NaN,NaN,NaN
4444,MIC1227_CP_Batch1_Plate1B_1_MMStack_A2-Site_10...,bai,APPrna_batch_1,1B,A2,102,measured/imaging/uint8/round_1/batch1/MIC1227_...,measured/imaging/uint8/round_1/batch1/MIC1227_...,measured/imaging/uint8/round_1/batch1/MIC1227_...,measured/imaging/uint8/round_1/batch1/MIC1227_...,...,CLL_BTCH_11971,Simvastatin::10uM::P046,10uM,3,treatment,False,NaN,NaN,NaN,NaN

        Treatment       original_treatment
4440  Simvastatin  Simvastatin::10uM::P046
4441  Simvastatin  Simvastatin::10uM::P046
4442  Simvastatin  Simvastatin::10uM::P046
4443  Simvastatin  Simvastatin::10uM::P046
4444  Simvastatin  Simvastatin::10uM::P046